### ISSUE TITLE
[Q] Compressor off and never starts on 12V

### ISSUE THREAD

**Issue by 0anton** [UnifiedEngineering/mobicool-fr34#1]
Hi Werner,

I've noticed a bit annoing behavior in FR34: it sometimes does not start compressor, when connected over 12V power. It gets then into strange state: the fan is working, power indicator shows green, but compressor is switched off (does not start). Needless to say, bad for the food in the fridge. The compressor never starts again unless special manipulation is down (as described below). The fan always keep working. Power off/on while keeping 12/24V does not help.  

It never happens on 220V mains. Mechanically there is apparently no problems, since it can be always recovered from that state.  Annoing is that it is not possible to (as least I could not find the way) to recover without access to 220V. To recover I connect it shortly to 220V, power-off-on cycle and it works again. The same does not work over the low voltage (12V or 24V).

My idea that the fridge compressor does not kick-in if it does not have enough of start current (maybe up to 10A if I understand it from other people response, though I measured max 6A, but not precise impulse measurement). And for some reason (bug in the firmware?) it remains in this state (compressor error, but shown as an error or low voltage on the screen).

Did you notice any parts in the firmware code, which maybe related to this behavior? If yes, is it possible to improve it in the firmware?

(I hesitate to replace the box using the garranty support, since I might get the same, if it is a design/software defect)

**Comment by xnk** [comment]
Do you get this behavior both with the original firmware and this alternative open one?

I also noticed that the compressor had issues turning on at low voltage levels when not enough current was available. The reason why this isn't noticeable when on mains 110V/230V is because the resulting 27V DC to the compressor board which results in a lot lower start-up current draw which the capacitors handles without issues. It was impossible to start with a 5A power supply set at 12V but it would start without issues at 18V. Powering it off a small lead acid 12V battery is not a problem though, and with this alternate firmware it also works great powered off a 18/20V cordless tool Li-Ion battery.

The compressor is controlled by a brushless motor controller with its own firmware (which isn't touched by this alternate firmware), and feedback from this controller is quite sparse. I never got anything that looked useful back from the controller. There's current sensing on both the fan and the compressor which can be used to determine whether the compressor is actually running or not, but when left on its own the BLDC controller repeatedly attempts to start the compressor. My experience was that it was better to try to start it at a slow-ish (but not too slow) speed. I can't remember how the original firmware did it but it was something similar.

**Comment by 0anton** [comment]
Thank you very much, Werner, for prompt reply and sharing your experiences. I've intuitively added DC-DC 12V->24V convertor to reduce the start current and will observer the function. You confirm it helped in your case too. Although I use a spare car starter battery capable to deliver 300A current, the coolbox schematic apparently has some deficits working from 12V. Strange is that once failed, the compressor nevery tries to start again, nor automatically neither after manual on/off (tried after short delay). Yesterday it run with only with fan for over 12 hours making all food warm.

I have another obvervation. One day leaving the camping site I had the fridge connected to the car 12V and noticed it starts and stops compressor in the loop. I didn't put much attention to this. After 4 hours the food get warm, so compressor never ever started. I have an ideat that that situation (staying over longer time in this start/stop cycle) has damaged some electric lines responsible for restarting, but I hardly imagine how it can be in practice (I'd expect it either work or not work at all).

I understand your point that compressor has its own controller, and main controller does not have any overload protection logic, which can be adjusted.

I still run the stock firmware. I wanted to know if the custom one can influence this only-fun-working-no-compressor state, which you answered.

**Comment by xnk** [comment]
The stock firmware had some issues for sure, but I never encountered anything as drastic as you’re experiencing. The compressor motor is a sensor-less one, so there are no separate sensor wires to go bad at least. I’m thinking that if you end up in this situation where the compressor refuses to start at 12V and no amount of power cycling (not just soft power off) will get it back online until you supply 24V or mains, the compressor might be bad (higher than expected starting torque required). I think you should have it exchanged under warranty and see if this problem is reduced or eliminated. Looking at your power consumption figures in your comparison it looks like the compressor is consuming a reasonable amount of power, so it’s not completely bad, at least when comparing to my two FR-34:s which looks very similar the one you have. These are cheap compressors that looks like Danfoss knockoffs so I’m sure they have better and worse days during manufacturing. It all comes down to how much of a hassle the warranty exchange is. On 7 Jul 2023, at 01:37, Anton Golubev ***@***.***> wrote:﻿
Thank you very much, Werner, for prompt reply and sharing your experiences. I've intuitively added DC-DC 12V->24V convertor to reduce the start current and will observer the function. You confirm it helped in your case too. Although I use a spare car starter battery capable to deliver 300A current, the coolbox schematic apparently has some deficits working from 12V. Strange is that once failed, the compressor nevery tries to start again, nor automatically neither after manual on/off (tried after short delay). Yesterday it run with only with fan for over 12 hours making all food warm.
I have another obvervation. One day leaving the camping site I had the fridge connected to the car 12V and noticed it starts and stops compressor in the loop. I didn't put much attention to this. After 4 hours the food get warm, so compressor never ever started. I have an ideat that that situation (staying over longer time in this start/stop cycle) has damaged some electric lines responsible for restarting, but I hardly imagine how it can be in practice (I'd expect it either work or not work at all).
I understand your point that compressor has its own controller, and main controller does not have any overload protection logic, which can be adjusted.
I still run the stock firmware. I wanted to know if the custom one can influence this only-fun-working-no-compressor state, which you answered.

**Comment by 0anton** [comment]
Thank you very much Werner for your knowledable opinion!

My key take aways are:
- the compressor might be bad, higher than expected starting torque required
- they may have better and worse days during manufacturing

Warranty exchange looks relatively simple. Dometic has already offered to send the device in. I'll do that after the season is over 🌞🙂

Greetings to Malmö and have a nice summer time!

**Comment by aaronegger** [comment]
Hi, i have the exact same issue.
I ordered the MCF40 on Amz Primeday. The box completly refused to operate using 12V DC. The battery monitor shut off the compressor, although the voltage never dropped below 12.6V (measured using an oscilloscope).

So i returned it an ordered a new one.
The new one worked, but after a few hours, i get the same issue as @0anton .
First everything works fine, but then the compressor refuses to start. The power led stays green and never goes off. Even if the fan stops after a long while the power led stays green. This means it can't be the battery monitor that causes this issue.
The source is an eb3a from bluetti, which has a stabilized 12V@10Amps Outlet.

I returned the cooling box and ordered a new one. The third.
An this has exact the same issue. At 12V the compressor stops working after several hours.
In both cases i have to disconnect the device and wait for 10-20s and then after reconnecting, everything works for a few hours again.

I thought that maybe the board has an logic error, that prevents the compressor being restarted, because the board thinks it is already running (power led green) and it should run until the temperature has been reached.

But the issue seems to be deeper, as the fan stopped after a long time, despite the target temperature has not been reached and also setting the temperature manually higher to pretend that it is already cool enough, the cycle is not reseted. After the temperature rises above the new value, the compressor will never be restarted.

If i switch directly to 230V without waiting the issue keeps persistent. It was mandatory to disconnect it for some seconds.
But if this has been done before, the cooling box is able to run with 230V without any issue.

I would test the custom firmware, but i have no idea how to flash it to the cooling box. Is there a manual or readme how to achieve this?

@xnk Thank you for sharing you work that you have done with this device!

**Comment by 0anton** [comment]
@aaronegger Thank you for sharing your experiences. I can confirm I have same experiences as you. Maybe the crowd intelligence will help to find the solution. Mine solution in a meanwhile is to use dc-dc converter  12>24V. It stabilizes the issue with still-stands on 12V. Still it is quite annoying the fridge is not stable at 12V…

**Comment by aaronegger** [comment]
I bought and received the 12V 24V step up converter and will test if this fixes the issue for me too.
I called the german mobicool support and they told me that this is indeed an issue. But also meant that this is a very rare issue and i am extremly unlucky that i have two devices in a row with exact the same issue. But if fixing the issue by supplying 24V, the issue has be to somewhere the 24V are used without being converted to 12V before.

**Comment by 0anton** [comment]
Great @aaronegger! Please share your experiences with the step-up converter!

**Comment by aaronegger** [comment]
I tested it with the step up converter for about 2 weeks and it worked just fine with it. I had never the issue that the compressor refused to start. I think this is a design flaw that occurs when running the thing with 12v..
